#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : check-manifest
Version  : 0.39
Release  : 7
URL      : https://files.pythonhosted.org/packages/7b/a9/1df7b7a07a1c224604cab18e27de9820b640e088c75f28cf7f77cfa17a72/check-manifest-0.39.tar.gz
Source0  : https://files.pythonhosted.org/packages/7b/a9/1df7b7a07a1c224604cab18e27de9820b640e088c75f28cf7f77cfa17a72/check-manifest-0.39.tar.gz
Summary  : Check MANIFEST.in in a Python package for completeness
Group    : Development/Tools
License  : MIT
Requires: check-manifest-bin = %{version}-%{release}
Requires: check-manifest-license = %{version}-%{release}
Requires: check-manifest-python = %{version}-%{release}
Requires: check-manifest-python3 = %{version}-%{release}
Requires: toml
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-mock
BuildRequires : python-mock-python
BuildRequires : toml
BuildRequires : tox
BuildRequires : virtualenv

%description
check-manifest
==============
|buildstatus|_ |appveyor|_ |coverage|_
Are you a Python developer?  Have you uploaded packages to the Python Package
Index?  Have you accidentally uploaded *broken* packages with some files
missing?  If so, check-manifest is for you.

%package bin
Summary: bin components for the check-manifest package.
Group: Binaries
Requires: check-manifest-license = %{version}-%{release}

%description bin
bin components for the check-manifest package.


%package license
Summary: license components for the check-manifest package.
Group: Default

%description license
license components for the check-manifest package.


%package python
Summary: python components for the check-manifest package.
Group: Default
Requires: check-manifest-python3 = %{version}-%{release}

%description python
python components for the check-manifest package.


%package python3
Summary: python3 components for the check-manifest package.
Group: Default
Requires: python3-core

%description python3
python3 components for the check-manifest package.


%prep
%setup -q -n check-manifest-0.39

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559879301
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/check-manifest
cp LICENSE.rst %{buildroot}/usr/share/package-licenses/check-manifest/LICENSE.rst
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/check-manifest

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/check-manifest/LICENSE.rst

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
